{% set name = "iosbackup" %}
{% set version = "0.9.923" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/iOSbackup-{{ version }}.tar.gz
  sha256: 2e97748b82dab3a79c2b43a188feea73b000916eaccc00365ce3aa8ef91bad58
  patches:
    - open.patch

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - nskeyedunarchiver
    - pycryptodome
  run:
    - nskeyedunarchiver
    - pycryptodome
    - python >=3.8

test:
  imports:
    - iOSbackup
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/avibrazil/iOSbackup
  summary: Reads and extracts files from password-encrypted iOS backups
  license: LGPL-2.0-or-later
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - ickc
