{% set name = "iosbackup" %}
{% set version = "0.9.925" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/iOSbackup-{{ version }}.tar.gz
  sha256: 33545a9249e5b3faaadf1ee782fe6bdfcdb70fae0defba1acee336a65f93d1ca
  patches:
    - open.patch

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - nskeyedunarchiver
    - pycryptodome
  run:
    - nskeyedunarchiver
    - pycryptodome
    - python >=3.8

test:
  imports:
    - iOSbackup
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/avibrazil/iOSbackup
  summary: Reads and extracts files from password-encrypted iOS backups
  license: LGPL-2.0-or-later
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - ickc
